version: '3.3'
services:
  db:
    image: postgres:14
    container_name: psql-con
    volumes: 
      #- ./sql/django.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./data/db:/var/lib/postgresql/data 
    hostname: db
    environment:
      - POSTGRES_DB=labocart
      - POSTGRES_USER=labouser
      - POSTGRES_PASSWORD=123

  web:
    restart: always
    image: prj-image
    container_name: prj-container
    build: 
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/code
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_NAME=labocart
      - POSTGRES_USER=labouser
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db     
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8050:8080     
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    # command: ./go
    volumes:
      - ./go:/code
    depends_on:
      - db  
