# Generated by Django 2.2 on 2022-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer', models.TextField(max_length=25)),
                ('name', models.TextField(max_length=25)),
                ('place', models.TextField(max_length=25)),
                ('work_type', models.BooleanField(default=False)),
                ('phone', models.BigIntegerField()),
                ('status', models.IntegerField(default=0)),
                ('job_title', models.CharField(default='none', max_length=20)),
                ('rate', models.IntegerField(default=500)),
                ('worker_name', models.TextField(max_length=25)),
                ('worker_uname', models.TextField(max_length=25)),
                ('worker_phone', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer', models.TextField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('place', models.TextField(max_length=255)),
                ('work_type', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='jobImages/')),
                ('phone', models.BigIntegerField()),
                ('status', models.IntegerField(default=0, null=True)),
                ('job_title', models.CharField(default='none', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('total_price', models.IntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
