# Generated by Django 2.2 on 2022-11-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer', models.TextField(max_length=25)),
                ('name', models.TextField(max_length=25)),
                ('place', models.TextField(max_length=255)),
                ('work_type', models.BooleanField(default=False)),
                ('phone', models.BigIntegerField()),
                ('status', models.IntegerField(default=0)),
                ('job_title', models.CharField(default='none', max_length=20)),
                ('rate', models.IntegerField(default=500)),
                ('worker_name', models.TextField(max_length=25)),
                ('worker_uname', models.TextField(max_length=25)),
                ('worker_phone', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy_status', models.BooleanField(default=False)),
                ('work_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='categoryImages/')),
            ],
        ),
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('subcountry', models.CharField(max_length=100, null=True)),
                ('geonameid', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirer', models.TextField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('place', models.TextField(max_length=255)),
                ('work_type', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.BigIntegerField()),
                ('status', models.IntegerField(default=0, null=True)),
                ('job_title', models.CharField(default='none', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('total_price', models.IntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0, max_length=20)),
                ('status', models.IntegerField(default=0, null=True)),
                ('amount', models.FloatField(default=0, max_length=20)),
                ('work_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.AppliedJobs')),
            ],
        ),
    ]
